### PR TITLE
Added TypeScript model

### PR DESCRIPTION
**Pull request by thegecko**
Inspired by your model I received at FullStack, I've created and built a TypeScript one. Please feel free to include it. I'm not sure how you created the instructions, however.

screen shot 2018-07-23 at 14 22 22

diyxotgwsaeljap

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Oh wow, that is so cool - great to see you've built it too :-)

I've just added one for D3, you can see the rendering here: https://www.mecabricks.com/en/models/BLvGWmx9vGy

**Comment by ColinEberhardt** [comment]
Did you build with metabricks? If so, can you make your model public and share it? Would be great to link to that too.

**Comment by thegecko** [comment]
I did. https://www.mecabricks.com/en/models/0DvY9yy9v9e

**Comment by ColinEberhardt** [comment]
Great - we'll need @godds to create an SVG version for the website. I'm going to see if I can find a way of generating that automatically, as it is a manual process at the moment.

**Comment by ColinEberhardt** [comment]
I've done some minor tweaks https://www.mecabricks.com/en/models/1k2qMX562E0 - will add it to the site shortly

**Comment by thegecko** [comment]
@ColinEberhardt Beware that without the back support, the model may be weaker in the bottom-middle due to there being a stack of 5 bricks not connected. I still got all pieces for about £4 :)

**Comment by godds** [comment]
@ColinEberhardt Your model is missing the brick for the 2nd foot.

SVG and instructions should be ready shortly.

**Comment by ColinEberhardt** [comment]
Oh no, then my order is going to be one brick short 😱

**Comment by godds** [comment]
That's all merged, tidied up and live now. Thank you @thegecko 👍

**Pull request merged**
