### PR TITLE
add python logo

### PR DESCRIPTION
**Pull request by jdhodges**
Model here: https://www.mecabricks.com/en/models/Dp2llXYA2MV

### CODE REVIEW

**Comment by godds** [comment]
Apologies, not sure how this has been missed to date. I've had a stab at slightly improving the model to use a sturdier brick arrangement and to adjust the height of the snake heads to better mimic to the official logo: https://mecabricks.com/en/models/N02gW0Gn2LD

Are you happy for us to go with this instead?

**Comment by jdhodges** [comment]
Sure, LGTM :+1:

**Comment by ColinEberhardt** [comment]
That looks very cool! @godds have you checked that these bricks are available on bricklink?

**Comment by godds** [comment]
All appear to be available on bricklink (now that I've switched the "background" to fully white). When I let bricklink auto-select the store, brick prices range from 3p to 13p with a total cost of £4.89. Is that reasonable?

**Comment by ColinEberhardt** [comment]
Yeah, £5 is a pretty typical cost. For other designs cost hasn't been an issue, rather it is availability. Some of the brick types that mecabricks let you select don't seem to exist!

**Comment by godds** [comment]
Cool, all good then. I will close this pull request and create an issue so we don't lose visibility while I do the other necessaries to add it to the site. Great stuff @jdhodges :-)

**Comment by godds** [comment]
Have (finally!) created the instructions, etc. and added directly to master, so that is live now. Many thanks @jdhodges

**Pull request closed without merging**
